name: encryption_project
description: A Dart project for encryption and decryption
environment:
  sdk: ">=2.12.0 <3.0.0"  # تحديد نطاق SDK المناسب لدعم Null Safety

dependencies:
  crypto: ^3.0.2
  encrypt: ^5.0.0
